[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[project]
name = "ramparils"
requires-python = ">=3.9"
classifiers = ["Programming Language :: Python :: 3"]
version = "0.2.0"
description = "ParamILS automated algorithm configuration (Rust, PyO3)"
readme = "README.md"

[project.urls]
Repository = "https://github.com/deeper4ai/ramparils"
Documentation = "https://deeper4ai.github.io/ramparils/"

[tool.maturin]
features = ["python"]    # enables PyO3 bindings
module-name = "ramparils._ramparils"
