[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[project]
name = "parils"
requires-python = ">=3.9"
classifiers = ["Programming Language :: Python :: 3"]
version = "0.1.0"
description = "ParamILS automated algorithm configuration (Rust, PyO3)"

[tool.maturin]
features = ["python"]    # enables PyO3 bindings
module-name = "parils._parils"
