# Starting strategy: defaults from params-eprover-nb5.txt.
nb5 = {
    "condense":            "1",
    "defcnf":              "4",
    "der":                 "stragg",
    "ext_sup_max_depth":   "0",
    "fool_unroll":         "true",
    "forwardcntxtsr":      "1",
    "fwdemod":             "1",
    "heur0":               "0",
    "heur1":               "1",
    "heur2":               "2",
    "heur3":               "3",
    "ho_order_kind":       "lfho",
    "inverse_recognition": "false",
    "lift_lambdas":        "true",
    "local_rw":            "true",
    "neg_ext":             "all",
    "no_eq_unfolding":     "1",
    "pos_ext":             "all",
    "prefer":              "0",
    "presat":              "1",
    "replace_inj_defs":    "false",
    "satcheck":            "ConjMinMinFreq",
    "sel":                 "SelectMaxLComplexAvoidAppVar",
    "simparamod":          "normal",
    "slots":               "4",
    "sos_input_types":     "1",
    "splaggr":             "0",
    "splcl":               "0",
    "srd":                 "0",
    "strong_rw_inst":      "1",
    "tord":                "KBO6",
    "tord_const":          "1",
    "tord_prec":           "invfreq",
    "tord_weight":         "precrank10",
}

# Default strategy (all params at their defaults from params-eprover.txt).
default = {
    "condense":            "0",
    "defcnf":              "24",
    "der":                 "none",
    "ext_sup_max_depth":   "-1",
    "fool_unroll":         "true",
    "forwardcntxtsr":      "0",
    "fwdemod":             "2",
    "heur0":               "0",
    "heur1":               "1",
    "heur2":               "2",
    "heur3":               "3",
    "ho_order_kind":       "lfho",
    "inverse_recognition": "false",
    "lift_lambdas":        "true",
    "local_rw":            "false",
    "neg_ext":             "off",
    "no_eq_unfolding":     "0",
    "pos_ext":             "off",
    "prefer":              "0",
    "presat":              "0",
    "replace_inj_defs":    "false",
    "satcheck":            "none",
    "sel":                 "SelectMaxLComplexAvoidPosPred",
    "simparamod":          "none",
    "slots":               "4",
    "sos_input_types":     "0",
    "splaggr":             "0",
    "splcl":               "0",
    "srd":                 "0",
    "strong_rw_inst":      "0",
    "tord":                "LPO4",
    "tord_const":          "0",
    "tord_prec":           "arity",
    "tord_weight":         "arity",
}

